M_TO_NM = 0.000539957; NM_TO_M = 1/M_TO_NM
FT_TO_M = .3048; M_TO_FT = 1/FT_TO_M
FT_TO_NM = FT_TO_M*M_TO_NM
NM_TO_FT = 1/FT_TO_NM 
MB = 1000000

COLOR_LIST = ['blue', 'orange', 'green', 'red', 'black', 'purple']

DEFAULT_DATA_FILE_PATH = '../data/'

INITIAL_DIM = 3
UPDATE_DIM = 4
NUM_UPDATE_BYTE_SIZE = 2
INFO_BYTE_SIZE = 4
WAYPOINT_BYTE_SIZE = 8

STANDARD_NUM_PARTITIONS = 3

NUM_BINS_HISTOGRAM = 75

INDIV_AC_SCOPE = False
